
services:

  # Nginx and PHP fpm container
  web:
    build: 
      context: ./
    container_name: expense-tracker-web
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./:/var/www 
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    depends_on:
      - db

  # PostGres Database
  db:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: expenseTrackerDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
