version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:8XDRMOjbiHC581ZH0O1UFtHylRJGBWKbqHMZIMywPE4=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: expense_tracker
      DB_USERNAME: admin
      DB_PASSWORD: password
      SESSION_DRIVER: database
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: expense_tracker
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
